### ISSUE TITLE
Bot not appearing in correct langauge for user

### ISSUE THREAD

**Issue by pld** [goodbotai/karma#27]
### Environment
Production user using bot from Brazil

### Expected behavior
Bot appears in language based on user-profile

### Actual behavior
![photo_2017-09-11_11-17-26 copy](https://user-images.githubusercontent.com/50706/30279752-0d25e932-96dc-11e7-9a1c-8bd3e0044db8.jpg)

### Steps to reproduce the behavior
Reproduced by 2 people in Brazil

---

### Implementation plan

-
-
-

**Comment by urbanslug** [comment]
I believe this was fixed in https://github.com/goodbotai/karma/pull/33 but I will wait for user feedback before closing this.
