### ISSUE TITLE
Need to explain the lakert-scale emotion question number

### ISSUE THREAD

**Issue by ainulhamdani** [goodbotai/karma#29]
### Environment
Production user using bot from Indonesia
### Expected behavior
Explain the meaning of Likert-scale number
### Actual behavior
![karma](https://user-images.githubusercontent.com/7234044/30307246-62e7c7d6-97af-11e7-8ed5-09d7456984af.JPG)

### Steps to reproduce the behavior

---

### Implementation plan

-
-
-

**Comment by pld** [comment]
@ainulhamdani by explain, do you mean say which one is more and which is less of the question being asked?

**Comment by ainulhamdani** [comment]
@pld yes. I think it's just translation issue. In the English version, the number is being explained.
![karma4](https://user-images.githubusercontent.com/7234044/30323312-40958aca-97ef-11e7-882b-60eb0ba61a51.JPG)

**Comment by pld** [comment]
Cool, can you provide that additional text in Bahasa here, then we'll drop
it in later

**Comment by ainulhamdani** [comment]
1. Sangat Sedikit atau Tidak Sama sekali
2. Sedikit
3. Sedang
4. Agak Sangat
5. Sangat

**Comment by urbanslug** [comment]
@pld @ainulhamdani For future reference you can easily make changes to the text by making pull requests for changes in this file https://github.com/goodbotai/karma/blob/master/translations/in.json 


For example in this case I will update line 14 https://github.com/goodbotai/karma/blob/master/translations/in.json#L14
