### ISSUE TITLE
Research a way to link users that refer other users to eachother

### ISSUE THREAD

**Issue by pld** [goodbotai/karma#30]
### Environment
all

### Expected behavior
We'd like to be able to store a link from a user that interacted with the bot to a user that referred them to the bot.

If they click on a share link is that information available?
If not, can we ask them to tell us who referred them in a way we can identify.

### Actual behavior
These are not linked together

**Comment by urbanslug** [comment]
We shall add a ref to the bot link the ref value shall be the referrer's Rapidpro contact ID.

Basically we shall have the URL here https://github.com/goodbotai/karma/blob/master/karma.js#L389 be http://m.me/1504460956262236?ref=<RapidPro ID>

**Comment by pld** [comment]
That approach sounds good. This means that for everyone that joins by
clicking on a link that they've received from another user of Karma, we'll
know the connection between that new user and the person who referred them
(so a backwards link).

Is this closed, did you make this change already?

**Comment by urbanslug** [comment]
No I'll make the change op close #24
