### ISSUE TITLE
Bot not responding to new facebook account

### ISSUE THREAD

**Issue by deemree** [goodbotai/karma#48]
Happened when a new facebook account ( the account that never contact the bot previously) try to message the bot for the first time.

![image](https://user-images.githubusercontent.com/32631722/32157423-6a956464-bd54-11e7-83e0-20ccf66aeb94.png)

**Comment by urbanslug** [comment]
This happens when users who aren't referred by other users to the bot start using the bot so we have a problem creating their account.

Sentry error:
```
Promise rejected: Failed to fetch Facebook profile in createUserAndStartConversation: TypeError: Cannot read property 'ref' of undefined
```

thrown here: https://github.com/goodbotai/karma/blob/master/karma.js#L420
