### ISSUE TITLE
Changing the name of the bot when it's shared with new user

### ISSUE THREAD

**Issue by deemree** [goodbotai/karma#58]
![image](https://user-images.githubusercontent.com/32631722/32536684-7ca37128-c470-11e7-9245-c86df0d9622b.png)

The new user sees "Hello, I'm Karma" - instead it should show "Hello, I'm BEATS"

**Comment by deemree** [comment]
@urbanslug Let's pause on fixing this while I get a confirmation on what should the final name of the bot be,

**Comment by urbanslug** [comment]
BEATS was agreed upon a while back. I'll make this change.
