### ISSUE TITLE
Differing behavior when quitting in Bahasa vs English

### ISSUE THREAD

**Issue by deemree** [goodbotai/karma#61]
In Bahasa if we say 'No' to taking the survey at this time, the bot asks for a re-confirmation before quitting:
![image](https://user-images.githubusercontent.com/32631722/32538951-f5d64a18-c478-11e7-9f61-b697ada1d41d.png)

"Apa Anda yakin ingin berhenti?" = "Are you sure you want to quit"
It froze after that and had to be restarted (waited for 15 mins).

In English if we say 'No' to the same step - it didn't ask for a re-confirmation:
![image](https://user-images.githubusercontent.com/32631722/32538984-10bdbfbe-c479-11e7-987b-c234c494f0cd.png)

**Comment by deemree** [comment]
![image](https://user-images.githubusercontent.com/32631722/32647713-b31e1ad4-c603-11e7-9e4f-835dc75b2d64.png)

Instead of just the 'done', we should stick with the 'bye, you can start me...' so the user knows what to do next (and it's less abrupt).
@urbanslug maybe we get the new translation from SID?

**Comment by urbanslug** [comment]
I'll just use the quit message with 'bye, you can start me...'

**Comment by deemree** [comment]
@urbanslug is the "bye you can start me..." in Bahasa or English?
